[[INSTALLATION]]
* install-build-config-run
*install packages and build*
npm install --save-dev npm@7.24.1
npm install --save-dev typescript
npm run build

*edit configs and dotenv*
- .env
  L2_WEB3_ENDPOINTS=http://127.0.0.1:8545
  # secrets
  PRIVATE_KEY=blah


- src/configs/config.json

- mute noise BotService and PerpService
cp mylibs/BotService.js node_modules/@perp/common/build/lib/perp/BotService.js
cp mylibs/BotService.js node_modules/@perp/common/build/lib/eth/EthService.js

*execute*
env $(cat .env | grep -v '#' | xargs) npm run start



** run from debugger
launch.json
------------
{
      "name": "set env",
      "type": "node",
      "request": "launch",
      "args": [
        "${workspaceRoot}/src/index.ts"
      ],
      "env":{
        "L2_WEB3_ENDPOINTS":"http://127.0.0.1:8545",
        "PRIVATE_KEY":"blah"
      },
      "runtimeArgs": [
        "--nolazy",
        "-r",
        "ts-node/register"
      ],

* hardhat environment setup
**setup hardhat fork**
- install hardhat in a local directory
cd /Users/ayb/mio/code/tinker/dft/hh


- ensure using your own signer in local node
- hardhat.config.ts
------------------------
import { HardhatUserConfig } from 'hardhat/config';
import '@nomicfoundation/hardhat-toolbox';

export const BLOCK_NUMBER = 30306621;

const config: HardhatUserConfig = {
  solidity: {
    settings: {
      optimizer: {
        enabled: true,
        runs: 1000,
      },
    },
    compilers: [
      {
        version: '0.7.6',
      },
    ],
  },
  networks: {
    hardhat: {

accounts:[{privateKey:"blah",
balance:"10000000000000000000000"}],
      mining: {
        auto: true,
        mempool: {
          order: 'fifo',
        },
      },
    },
  },
};

export default config;

*run fork*
- steps
  - [ ] cd /Users/ayb/mio/code/tinker/dft/hh
  - [ ] ensure hardhat.config poinint to valid account
    - [ ] pk in hh.config to match what u have in visual config
      - [ ] e.g ea69cd89c97833a5a36098c0f231c21a5cd1f5af083878e870903a85efda7561 (SHOL_SHORT)

	  - [ ]  npx hardhat node --fork https://opt-mainnet.g.alchemy.com/v2/oH4_c4rONzDHSXUvSdFpuXAmgMpvsQIi  --fork-block-number 30306622

    
* WORKFLOWS
** deploy new change
   
*** local testing
- local testing can be against hardhat snapshot or live prod node (if already have open position)

**** hardhat-snapshot test. launch.json:hardhat
- see *run fork*


***** scenrios

******* Block:  BNB
- events
  - [ ] realized pnl: "4424242424242424"  <--------
  - [ ] positionChange:
    "exchangedPositionSize":"65496957121485175"
    "exchangedPositionNotional":"-22099090909090907880"
    "fee":"22121212121212120"
    "openNotional":"-22121212121212120000"
    "sqrtPriceAfterX96":"1455315141843266345934788422957"
	
- last open.swap
  - [ ] amount0 : -65496957121485175
       amount1 : 22165587672107229569
       sqrtPriceX96 : 1455315141843266345934788422957
       liquidity :317838935315989593923871
       tick :58215

  - state change
    - [ ] balance: 481835753433825467740 -> 481835924915803390
      
- s
  - [ ] scenario: SOLshort at 65131100
    - [ ] pair: (0x7Ca51ce88195eD6a2C7289DD1B286a713fbD806b,
    - [ ] uret: 0.9567
  - [ ] trigger onLoss, onScale by chaning MIN_RET/MAX_RET 96/95
  - [ ] hardhat supports only one signer. use 'bypass dotenv' debug config using only one
  - [ ] config turn false everything xcept solshort
    
- s [using live network] //in some cases may need to use hardhat
  - [X] use dot-env configuration
  - [ ] put debug breakpoints to avoid opening/closing

**** live prod node test. launch.json:use-dotenv       
*** deploy in DO   
- local
  - [ ] git commit src/arbitrageur/Arbitrageur.ts -m blah
  - [ ] git push origin qa

- DO    
  - [ ] git tag pre-holos; git tak //label befor you pull to be able to roll back
    - [ ] git checkout pre-holos to rollback
  - [ ] cp src/configs/config.json src/configs/bkp.config.jsonbkp copyof config.json
  - [ ] DO: git pull

*** UAT in DO



[[* CODE INFO]]
** metadata
/Users/ayb/mio/code/dfi/egor/node_modules/@perp/curie-deployments/optimism/core/metadata.json   
* GOTCHAS
** debugger acting weird

- prob: e.g disappering or breaking in wrong place. 
- remedy: delete all breakpoints and set again. stop debugger. save and restart

** hardhat limitations
- hardhat use only one signer (first account on the config) can only test one market
at a time
